server:
  port: 8081
  
spring:  application:    name: OMSAPP
  batch:
    job:
      enabled: false  
  datasource:    url: jdbc:mysql://localhost:3306/testDb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: false
        show_sql: false
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB          